var content_json="";var duration=0;var length=0;var temp_length=0;var id_row=1;var currentCurationVidId="";var temp_id_row=0;var save=0;var is_row_edited=0;var is_row_null=0;var is_row_nan=0;var source_of_the_video="";var is_video_published=false;curation_handle=new curate_libs;$(function(){if(moveToCuration)curateVideoFromVideoId(data.videoID)});
function getYoutubeListData(queryStr){var xhrObj=new CommonUtils.remoteCallClass;var dataObj=parseQueryStringToObject(queryStr);dataObj["server"]="youtube";xhrObj.requestData={"request":"search_data","data":dataObj};xhrObj.asyncPostRequest("./"+dataRequestURL,function(response){progressChange(70);response=JSON.parse(response);var validateResponseCheck=validateAppResponse(response);if(validateResponseCheck){youtubeListFlag=true;data["list"]=response.data;renderListData();progressChange(100)}else{data["list"]=
[];renderListData();progressChange(100)}})}var curateVideo=function(event){$("#curateScrollContainer .curationTablebody").html("");sourcevideoID=$(event.target).closest(".list-item-row[data-sourcevidId]").attr("data-sourcevidId");$("#list.section").css("display","none");$("#curationInformation, #curationTopics").css("display","block");LoadVideoforCuration(sourcevideoID,source_of_the_video)};
var watchVideoCurate=function(event){$("body").animate({"scrollTop":0},1E3);data.videoID=$(event.target).closest(".list-item-row[data-sourcevidId]").attr("data-sourcevidId");vidPlayerObject.LoadNewVideoByID(data.videoID,0);$(".list-item-row.expand").removeClass("expand").find(".content-toggle").removeClass("open")};
$(function(){$("#listContainer").on("click",".media-toggle-link.watch",watchVideoCurate);$("#listContainer").on("click",".media-toggle-link.curate",curateVideo);$(".curationTablebody").on("click",".editRow .curationCell:nth-child(2) span",function(){$(this).html(vidPlayerObject.GetCurrentPTS().toFixed(1));save=0});$(".curationTablebody").on("click",".editRow .curationCell:nth-child(3) span",function(){$(this).html(vidPlayerObject.GetCurrentPTS().toFixed(1));save=0});$(".curationTablebody").on("click",
".editRow .curationCell:nth-child(5)",function(event){$(".editRow").removeClass("editRow");$(".curationTablebody").find('[contenteditable="true"]').attr("contenteditable",false);event.stopImmediatePropagation()});$(".curationTablebody").on("click",".editRow .curationCell:nth-child(4)",function(event){vidPlayerObject.Play();$(".editRow").removeClass("editRow");$(".curationTablebody").find('[contenteditable="true"]').attr("contenteditable",false);response=curation_handle.correct_the_timings(event);
if(typeof response!="undefined"){if(typeof response.is_row_null!="undefined")is_row_null=!response.is_row_null?0:1;if(typeof response.is_row_edited!="undefined")is_row_edited=!response.is_row_edited?0:1;if(typeof response.is_row_nan!="undefined")is_row_nan=!response.is_row_nan?0:1}event.stopImmediatePropagation()});$(".curationTablebody").on("click",".curationCell:nth-child(6)",function(event){$(".editRow").removeClass("editRow");$(event.target).closest(".curationRow").remove();rows=$("#curateScrollContainer .curationTablebody .curationRow").length;
for($i=0;$i<rows;$i++)$($("#curateScrollContainer .curationTablebody .curationRow")[$i]).attr("id_row",$i+1);save=0});$("#curate_language").on("change",function(e){var optionSelected=$("option:selected",this);var valueSelected=this.value;if(valueSelected=="other_language")$("#curate_other_language").focus();save=0});$("#curate_category").on("change",function(e){var optionSelected=$("option:selected",this);var valueSelected=this.value;if(valueSelected=="other_category")$("#curate_other_category").focus();
save=0});$(".curationTablebody").on("click",".curationCell:nth-child(5)",function(){var start_time=$(this).prev().prev().prev().text();var end_time=$(this).prev().prev().text();newSegInfo=curation_handle.CreateSegment(1)[0];length=newSegInfo.segmentList.length;content_json=curation_handle.CreateSegment(1)[1];temp_id_row=Number($(this).parent().attr("id_row"))-1;$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive");$($("#curateScrollContainer .curationTablebody .curationRow")[temp_id_row]).addClass("playActive");
vidPlayerObject.LoadNewVideoSegment(newSegInfo.videoID,"handle_segmentwise");vidPlayerObject.PlaySegmentwise(start_time,end_time)});$(".curationTablebody").on("click",".curationCell:nth-child(4)",function(){$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive");vidPlayerObject.Pause();temp_row=$(".editRow").attr("id_row");temp_total_row=$("[id_row]").length;if(temp_row!=undefined){response=curation_handle.correct_the_timings(0,temp_row,temp_total_row);if(typeof response!=
"undefined"){if(typeof response.is_row_null!="undefined")is_row_null=!response.is_row_null?0:1;if(typeof response.is_row_edited!="undefined")is_row_edited=!response.is_row_edited?0:1;if(typeof response.is_row_nan!="undefined")is_row_nan=!response.is_row_nan?0:1}}$(".editRow").removeClass("editRow");var curationRow=$(this).closest(".curationRow");curationRow.addClass("editRow");$(".curationTablebody").find('[contenteditable="true"]').attr("contenteditable",false);curationRow.find("span:lt(4)").attr("contenteditable",
true)});$("#curate_keywords").html($("#curate_keywords").html().trim());$("#add_new_topic").on("click",add_new_topic);$("#save_curation").on("click",publish);$("#publish_curation").on("click",final_publish);$("#curate_title #curate_description #curate_keywords").on("input",function(){save=0});$("#curate_age").on("change",function(e){save=0});$("#curateBackToList").on("click",function(){if(save==0&&!is_video_published)if(!confirm("Curation has not been saved. Do you wish to leave curation?"))return false;
save=1;$('input[type="text"]').val("");if(moveToCuration){history.go(-1);return true}$("#curationInformation, #curationTopics").css("display","none");$("#list.section").css("display","block");vidPlayerObject.UnloadVideo();event.preventDefault()});var curationCategoryArray=curationOptions["categories"];var curationLanguageArray=curationOptions["languages"];for(var key in curationCategoryArray)$("#curate_category").append('<option value="'+key+'">'+curationCategoryArray[key]["catName"]+"</option>");
$("#curate_category").append('<option value="other_category">other</option>');for(var key in curationLanguageArray)$("#curate_language").append('<option value="'+key+'">'+curationLanguageArray[key]["language"]+"</option>");$("#curate_language").append('<option value="other_language">other</option>')});
function LoadVideoforCuration(id,source){$("#save_curation").html("Save");$("#publish_curation").html("Publish");is_video_published=false;$.ajax({url:"./"+dataRequestURL+"?request=yt_metadata_for_curation&data[id]="+id+"&data[source]=yt",type:"GET",success:function(response){var response=JSON.parse(response);if(response["status"]==true){response=response["data"];duration=curation_handle.ytduration_to_sec(response["metadata"]["items"][0]["contentDetails"]["duration"]);source_of_the_video=response["metadata"]["source"];
response=response["metadata"]["items"][0]["snippet"];$("#curate_title").val(response["title"]);$("#curate_description").val(response["description"]);if(response["tags"]!=null&&response["tags"]!="")$("#curate_keywords").html(response["tags"].join(","));$("#curate_category").val(curationVideoCategory)}}});if(playerReady){vidPlayerObject.LoadNewVideoByID(id,0);currentCurationVidId=id;vidPlayerObject.Play()}else setTimeout(function(){load_video_after_api(id)},1500)}
function load_video_after_api(id){if(playerReady){vidPlayerObject.LoadNewVideoByID(id,0);vidPlayerObject.Play();currentCurationVidId=id}else setTimeout(function(){load_video_after_api(id)},1500)}function handle_segmentwise(){vidPlayerObject.PlaySegmentwise(newSegInfo.segmentList[0].endTime,duration);vidPlayerObject.Pause();$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive")}function unload(){if(save==0)return"Video has not been saved..."}
function playSegments(num){temp_length=0;temp_id_row=0;temp_row=$(".editRow").attr("id_row");temp_total_row=$("[id_row]").length;$(".curationTablebody .curationRow").removeClass("editRow");if(num==0){newSegInfo=curation_handle.CreateSegment(0)[0];length=newSegInfo.segmentList.length;content_json=curation_handle.CreateSegment(1)[1]}else{newSegInfo=curation_handle.CreateSegment(1)[0];length=newSegInfo.segmentList.length;content_json=curation_handle.CreateSegment(1)[1]}vidPlayerObject.LoadNewVideoSegment(newSegInfo.videoID,
"HandleSegmentEnd");if(temp_row!=undefined){response=curation_handle.correct_the_timings(0,temp_row,temp_total_row);if(typeof response!="undefined"){if(typeof response.is_row_null!="undefined")is_row_null=!response.is_row_null?0:1;if(typeof response.is_row_edited!="undefined")is_row_edited=!response.is_row_edited?0:1;if(typeof response.is_row_nan!="undefined")is_row_nan=!response.is_row_nan?0:1}}$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive");$($("#curateScrollContainer .curationTablebody .curationRow")[temp_id_row]).addClass("playActive");
$(".curationTablebody").find('[contenteditable="true"]').attr("contenteditable",false);if(newSegInfo.segmentList[temp_length].startTime==""||newSegInfo.segmentList[temp_length].endTime==""){newSegInfo.segmentList[temp_length].startTime=0;newSegInfo.segmentList[temp_length].endTime=duration}vidPlayerObject.PlaySegmentwise(newSegInfo.segmentList[temp_length].startTime,newSegInfo.segmentList[temp_length].endTime)}
function HandleSegmentEnd(){if(temp_length+1==length){$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive");vidPlayerObject.PlaySegmentwise(newSegInfo.segmentList[temp_length].endTime,duration);vidPlayerObject.Pause()}else{temp_length++;temp_id_row++;$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive");$($("#curateScrollContainer .curationTablebody .curationRow")[temp_id_row]).addClass("playActive");vidPlayerObject.PlaySegmentwise(newSegInfo.segmentList[temp_length].startTime,
newSegInfo.segmentList[temp_length].endTime)}}
function publish(event){if(is_video_published||!playerReady)return false;vidPlayerObject.Pause();content_json=curation_handle.save_topics();is_row_null=0;is_row_edited=0;is_row_nan=0;$(".editRow").removeClass("editRow");$("#curateScrollContainer .curationTablebody .curationRow").removeClass("playActive");$(".curationTablebody").find('[contenteditable="true"]').attr("contenteditable",false);temp_length=$(".curationTablebody .curationRow").length;for(i=1;i<=temp_length;i++){response=curation_handle.correct_the_timings(0,
i,temp_length);if(typeof response!="undefined"){if(typeof response.is_row_null!="undefined")is_row_null=!response.is_row_null?0:1;if(typeof response.is_row_edited!="undefined")is_row_edited=!response.is_row_edited?0:1;if(typeof response.is_row_nan!="undefined")is_row_nan=!response.is_row_nan?0:1}}if(is_row_edited==1){alert("some timings has been altered.");is_row_edited=0;is_row_null=0;is_row_nan=0;return false}else if(is_row_null==1){alert("Please fix some blank timings.");is_row_null=0;is_row_edited=
0;is_row_nan=0;return false}else if(is_row_nan==1){alert("Timings should be number.");is_row_null=0;is_row_edited=0;is_row_nan=0;return false}curation_handle.title=$("#curate_title").val();curation_handle.description=$("#curate_description").val();other_category_value=$("#curate_category").val();if(other_category_value=="other_category")curation_handle.other_category=$("#curate_other_category").val();else curation_handle.other_category="";curation_handle.category=$("#curate_category").val();other_language_value=
$("#curate_language").val();if(other_language_value=="other_language")curation_handle.other_language=$("#curate_other_language").val();else curation_handle.other_language="";curation_handle.language=$("#curate_language").val();curation_handle.age=$("#curate_age").val();curation_handle.keywords=$("#curate_keywords").val();curation_handle.items=$("#curate_items").val();$("#save_curation").html("<img src='./"+projectFolderName+"/image/review_loading.gif' style='width:25%'></span>Saving");curation_handle.ajax_url=
"./"+dataRequestURL;curation_handle.source=source_of_the_video;curation_handle.topic_info=content_json;if(!curation_handle.save_curation(event,0)){$("#save_curation").html('<span style="font-family: Arial Unicode MS, Lucida Grande">&#10008;</span>Save');return false}else return true}
function final_publish(event){if(is_video_published)return false;if(save==0)if(!publish(event))return false;$("#publish_curation").html("<img src='./"+projectFolderName+"/image/review_loading.gif' style='width:25%'></span>Publishing");curation_handle.url="./"+dataRequestURL;curation_handle.save_curation(event,1)}
function on_ajax_response(event,data){if(event.target.id=="save_curation")if(data["status"]==false){$("#save_curation").html('<span style="font-family: Arial Unicode MS, Lucida Grande">&#10008;</span>Save');alert(data["error"])}else{if(data["status"]==true){$("#save_curation").html('<span style="font-family: Arial Unicode MS, Lucida Grande">&#10004;</span>Save');save=1}}else if(event.target.id="publish_curation")if(data["status"]==false){$("#save_curation").html('<span style="font-family: Arial Unicode MS, Lucida Grande">&#10008;</span>Save');
alert(data["error"])}else if(data["status"]==true){$("#save_curation").html('<span style="font-family: Arial Unicode MS, Lucida Grande">&#10004;</span>Save');$("#publish_curation").html('<span style="font-family: Arial Unicode MS, Lucida Grande">&#10004;</span>Publish');is_video_published=true}}function add_new_topic(){curation_handle.add_new_topic()}
var curateVideoFromVideoId=function(videoID){$("#curateScrollContainer .curationTablebody").html("");sourcevideoID=videoID;$("#list.section").css("display","none");$("#curationInformation, #curationTopics").css("display","block");LoadVideoforCuration(sourcevideoID,source_of_the_video)};