var renderSearchListOnDataReady=function(){data.searchYT&&data.list.ytList.list||!data.searchYT?(renderListData(),progressChange(100),data.searchYT=!1):setTimeout(function(){renderSearchListOnDataReady()},100)},renderListData=function(){if("view"==page)return!0;unloadCurrentVideo();UI_unBlockInterface();resetfilterUI();var a=data.list,b=a.documents;$("#listContainer").html("");var c="";b||data.searchFlag||!data.list.ytList.list||data.filters||(youtubeListFlag||(data.list.documents=[]),a=data.list,
b=a.documents);if(b){newListObject=new _ListWidget_.createList(a);data.modify=!0;$("#listContainer").append('<div class="container-fluid"></div>');if(youtubeListFlag)$("#curationInformation, #curationTopics").css("display","none"),""==vidPlayerObject&&(vidPlayerObject=new CreatePlayerWidget("YT","YTPlayerDiv","100%","100%",!0,!0)),newListObject.generateYoutubeList("#listContainer > .container-fluid"),$("#listContainer > .container-fluid").addClass("scrollableListContainer"),$("#listContainer > .container-fluid").enscroll({showOnHover:!0,
verticalTrackClass:"track3",verticalHandleClass:"handle3"});else{if(b.length<resultRows&&!data.searchFlag&&data.list.ytList.list&&!data.filters){c=0;0<a.start-a.numFound&&(c=a.start-a.numFound);for(var b=Math.min(resultRows,data.list.ytList.list.documents.length-c)-b.length,d=0;d<b;d++)data.list.documents.push(data.list.ytList.list.documents[c]),c++}newListObject.generateListPageList("#listContainer > .container-fluid");data.searchFlag||newListObject.createCategoryFilter();newListObject.createSourceFilter()}$(".content-desccription, .content-topics").each(function(){$(this).enscroll({showOnHover:!0,
verticalTrackClass:"track3",verticalHandleClass:"handle3"})});d=Math.ceil(a.numFound/a.rows)-1;youtubeListFlag||data.searchFlag||!data.list.ytList.list||data.filters||(d=Math.ceil((a.numFound+data.list.ytList.list.documents.length)/a.rows)-1);b=a.start/a.rows;if(0<d){c="";if(youtubeListFlag)c+='<li><a href="#" aria-label="Previous"><span aria-hidden="true">Previous</span></a></li><li><a href="#" aria-label="Next"><span aria-hidden="true">Next</span></a></li>';else{for(var c=c+'<li><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>',
e=0;e<=d;e++)c+="<li ",b==e&&(c+='class="active" '),c+='data-pageindex="'+e+'"><a href="#">'+(e+1)+"</a></li>";c+='<li><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>'}$("#listContainer").append('<div id="paginationContainer" class="text-center"><ul class="pagination">'+c+"</ul></div>");0==b&&$("#paginationContainer").find("li:first-child").addClass("disabled");b==d&&$("#paginationContainer").find("li:last-child").addClass("disabled");c=Math.max(b-paginationLimitIndex/
2,0);$("#paginationContainer li[data-pageindex]:nth-child(n+"+Math.max(b+paginationLimitIndex/2+1,paginationLimitIndex+2)+")").css("display","none");$("#paginationContainer li[data-pageindex]:nth-child(-n+"+c+")").css("display","none");UI_bindFunction("#paginationContainer li a",BindPaginationLinks,"click")}start=a.start}else $("#listContainer").append("<p><strong>No result found</strong><p>"),$("#listcategories .catfilteritem").not(".dummyEntry").remove(),data.modify=!0},openContentInfo=function(a){var b=
$(a.target).closest(".list-item-row");b.toggleClass("expand");b=b.find(".content-toggle");b.toggleClass("open");var c=$(".content-data.content-toggle.row.open").not(b);c.closest(".list-item-row").toggleClass("expand");c.toggleClass("open").find(".content-topics > div:first-child").toggleClass("hidden-sm").toggleClass("hidden-xs");b.find(".content-topics > div:first-child").toggleClass("hidden-sm").toggleClass("hidden-xs");a.preventDefault();a.stopPropagation()},filterListByCategory=function(a){data.filters=
!0;start=0;data.listFilter.category=$(a.currentTarget).attr("data-catfilter");getSearchData("keyword","",a)},filterListByLanguage=function(a){"0"!=a.currentTarget.value?(data.filters=!0,data.listFilter.language=$(a.currentTarget).val()):(data.listFilter.language=!1,data.listFilter.category||data.listFilter.age||(data.filters=!1));start=0;var b="keyword";data.searchFlag&&(b="category");getSearchData(b,data.lastSearchCat,a)},filterListByAge=function(a){a.currentTarget.checked?ageFilterArr[a.currentTarget.value]=
!0:delete ageFilterArr[a.currentTarget.value];data.filters=!0;start=0;var b="keyword";data.searchFlag&&(b="category");if(0!=Object.keys(ageFilterArr).length){var c="",d;for(d in ageFilterArr)ageFilterArr[d]&&(""!=c&&(c+=","),c+=d);data.listFilter.age=c}else data.listFilter.age=!1,data.listFilter.language||data.listFilter.category||(data.filters=!1);getSearchData(b,data.lastSearchCat,a)},resetListFilters=function(a){data.filters=!1;data.listFilter.category=!1;data.listFilter.language=!1;data.listFilter.age=
!1},resetfilterUI=function(){if(data.filters){if(data.listFilter.language?$("#language-select").find('option[value="'+data.listFilter.language+'"]').prop("selected",!0):$("#language-select").find('option[value="0"]').prop("selected",!0),$(".age-filter").each(function(){$(this).prop("checked",!1)}),ageFilterArr={},data.listFilter.age)for(var a=data.listFilter.age.split(","),b=0;b<a.length;b++)ageFilterArr[a[b]]=!0,$('.age-filter[value="'+a[b]+'"]').prop("checked",!0)}else $("#language-select").find('option[value="0"]').prop("selected",
!0),$(".age-filter").each(function(){$(this).prop("checked",!1)}),ageFilterArr={}};