$(function(){0!=$('[data-toggle="tooltip"]').length&&$('[data-toggle="tooltip"]').tooltip()});
var gUIElement=[],UI_applyTheme=function(a,b,c){if(0==$(a).length)return!1;a=$(a);classStr=c;switch(b){case "primary":classStr+="primary";break;case "success":classStr+="success";break;case "info":classStr+="info";break;case "warning":classStr+="warning";break;case "danger":classStr+="danger";break;default:classStr+="default"}a.addClass(classStr)},UI_bindFunction=function(a,b,c){if(0==$(a).length)return!1;Elem=$(a);($.isFunction(b)||"string"==typeof b&&$.isFunction(window[b]))&&Elem.each(function(){$(this).on(c,
function(a){if("string"==typeof b)window[b](a);else b(a)})})},UI_createButton=function(a,b,c,d,e){if(0==$(a).length)return!1;$(a).each(function(){$(this).addClass("btn");this.hasAttribute("data-button")&&$(this).text($(this).attr("data-button"));if(""==b||null==b)b="auto";if(""==c||null==c)c="auto";$(this).css({width:b,height:c});""!=d&&null!=d&&UI_bindFunction($(this),d,"click");UI_applyTheme($(this),e,"btn-")})},UI_getInputValue=function(a,b){if(0==$(a).length)return!1;var c=$(a);switch(b){case "string":c.val();
break;case "int":parseInt(c.val());break;case "float":parseFloat(c.val());break;case "bool":switch(c.attr("type")){case "checkbox":c.prop("checked");break;case "radio":c.prop("selected");default:""==c.val()||null==c.val()||c.val()}break;default:c.val()}},UI_createModal=function(a,b,c,d,e,h,g){if(0==$(a).length)return!1;a=$(a);a.addClass("modal fade");a.attr({role:"dialog","aria-labelledby":"bsUIModal"});0==$("body").find($(c)).length&&"string"==typeof c?a.append(c):0!=$("body").find($(c)).length&&
(a.append($(c)[0].outerHTML),$(c).remove());0==$("body").find($(b)).length&&"string"==typeof b?a.append(b):0!=$("body").find($(b)).length&&(a.append($(b)[0].outerHTML),$(b).remove());0==$("body").find($(d)).length&&"string"==typeof d?a.append(d):0!=$("body").find($(d)).length&&(a.append($(d)[0].outerHTML),$(d).remove());0==a.find(".modal-dialog").length&&a.children().wrapAll('<div class="modal-dialog" role="document"></div>');b=a.find(".modal-dialog");0==a.find(".modal-content").length&&b.children().wrapAll('<div class="modal-content"></div>');
b=a.find(".modal-content");0==a.find(".modal-header").length&&b.children().eq(0).wrap('<div class="modal-header"></div>');c=a.find(".modal-header");0==a.find(".modal-body").length&&b.children().eq(1).wrap('<div class="modal-body"></div>');a.find(".modal-body");0==a.find(".modal-footer").length&&b.children().eq(2).wrap('<div class="modal-footer"></div>');a.find(".modal-footer");c.prepend('<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>');
e&&UI_bindFunction(a,e,"show.bs.modal");g&&UI_bindFunction(a,g,"hide.bs.modal");h&&a.modal("show")},UI_bindModalButton=function(a,b){$(a).attr({"data-toggle":"modal","data-target":b})},UI_openModal=function(a){$(a).modal("show")},UI_closeModal=function(a){$(a).modal("hide")},UI_resetModal=function(a,b){$(a).find(".modal-header,.modal-body,.modal-footer").html("");b&&$(a).off("show.bs.modal")},UI_createTooltip=function(a,b,c,d){if(0==$(a).length)return!1;a=$(a);a.each(function(){this.hasAttribute("title")?
$(this).attr("data-title",$(this).attr("title")):this.hasAttribute(b)?$(this).attr("data-title",$(this).attr(b)):$(this).attr("data-title",b);if(""==c||null==c||void 0==c)c="bottom";$(this).attr({"data-html":!0,"data-toggle":"tooltip","data-placement":c})});a.tooltip();d&&UI_bindFunction(a,d,"show.bs.tooltip")},UI_showTooltip=function(a){if(0==$(a).length)return!1;$(a).tooltip("show")},UI_hideTooltip=function(a){if(0==$(a).length)return!1;$(a).tooltip("hide")},UI_toggleTooltip=function(a){if(0==$(a).length)return!1;
$(a).tooltip("toggle")},UI_destroyTooltip=function(a){if(0==$(a).length)return!1;$(a).tooltip("destroy")},UI_createTextBox=function(a,b,c,d){if(0==$(a).length)return!1;$(a).each(function(){$(this).addClass("form-group");if(""==b||null==b||void 0==b)b="text";this.hasAttribute(c)?$(this).append('<label for="'+$(this).attr("id")+'">'+$(this).attr(c)+"</label>"):this.hasAttribute("data-label")?$(this).append('<label for="'+$(this).attr("id")+'">'+$(this).attr("data-label")+"</label>"):""!=c&&null!=c&&
void 0!=c&&$(this).append('<label for="'+$(this).attr("id")+'">'+c+"</label>");if(this.hasAttribute(d))d=$(this).attr(d);else if(this.hasAttribute("data-placeholder"))d=$(this).attr("data-placeholder");else if(""==d||null==d||void 0==d)d="";$(this).append('<input type="'+b+'" class="form-control" placeholder="'+d+'" id="'+$(this).attr("id")+'" />');$(this).removeAttr("id")})},UI_preAddon=function(a,b,c,d){if(0==$(a).length)return!1;var e=$(a);c?e.each(function(){$(this).parent(".form-group").addClass("has-feedback");
-1!=b.indexOf("glyphicon")?$(this).before('<span class="glyphicon '+b+' form-control-feedback" aria-hidden="true"></span>'):$(this).before('<span class="form-control-feedback" aria-hidden="true">'+b+"</span>")}):e.each(function(){$(this).parent().hasClass("input-group")||$(this).wrap('<div class="input-group"></div>');-1!=b.indexOf("glyphicon")?$(this).before('<div class="input-group-addon"><span class="glyphicon '+b+' " aria-hidden="true"></span></div>'):$(this).before('<div class="input-group-addon">'+
b+"</div>")});d&&e.each(function(){UI_bindFunction(e.before(),d,"click")})},UI_postAddon=function(a,b,c,d){if(0==$(a).length)return!1;var e=$(a);c?e.each(function(){$(this).parent(".form-group").addClass("has-feedback");-1!=b.indexOf("glyphicon")?$(this).after('<span class="glyphicon '+b+' form-control-feedback" aria-hidden="true"></span>'):$(this).after('<span class="form-control-feedback" aria-hidden="true">'+b+"</span>")}):e.each(function(){$(this).parent().hasClass("input-group")||$(this).wrap('<div class="input-group"></div>');
-1!=b.indexOf("glyphicon")?$(this).after('<div class="input-group-addon"><span class="glyphicon '+b+' " aria-hidden="true"></span></div>'):$(this).after('<div class="input-group-addon">'+b+"</div>")});d&&e.each(function(){UI_bindFunction(e.next(),d,"click")})},UI_createCheckBox=function(a,b){if(0==$(a).length)return!1;var c=$(a);c.each(function(){$(this).addClass("checkbox");$(this).append('<label><input type="checkbox" id="'+$(this).attr("id")+'"/>'+$(this).attr("data-label")+"</label>");$(this).removeAttr("id")});
b&&UI_bindFunction(c,b,"change")},UI_createRadioBox=function(a,b){if(0==$(a).length)return!1;var c=$(a);c.each(function(){$(this).addClass("radio");$(this).append('<label><input type="radio" name="'+$(this).attr("name")+'" id="'+$(this).attr("id")+'" value="'+$(this).attr("data-value")+'" />'+$(this).attr("data-label")+"</label>");this.hasAttribute("checked")&&$(this).find('input[type="radio"]').attr("checked",!0);$(this).removeAttr("name id value")});b&&UI_bindFunction(c,b,"change")},UI_openBlockingDiv=
function(a){if(0==$(a).length)return!1;$(a).modal("show")},UI_closeBlockingDiv=function(a){if(0==$(a).length)return!1;$(a).modal("hide")},UI_setInputValue=function(a,b,c){if(0==$(a).length)return!1;a=$(a);"checkbox"==c||"radio"==c?a.prop("checked",b):a.val(b)},UI_createTable=function(a,b,c){if(0==$(a).length)return!1;$(a).each(function(){$(this).addClass("table-responsive");$(this).append('<table class="table" id="'+$(this).attr("id")+'"><thead></thead><tbody></tbody></table>');for(var a=$(this).find("thead"),
e=$(this).find("tbody"),h=b.length,g=b[0].length,f,l,m=0;m<h;m++)if(f=b[m],0<m){e.append("<tr></tr>");l=e.find("tr:last-child");for(var k=0;k<g;k++)l.append("<td>"+f[k]+"</td>")}else for(a.append("<tr></tr>"),l=a.find("tr"),k=0;k<g;k++)l.append("<th>"+f[k]+"</th>");(""!=c&&null!=c||void 0!=c)&&$(this).find(".table").addClass(c)})},UI_createTabs=function(a,b){if(0==$(a).length)return!1;var c=$(a);c.each(function(){$(this).addClass("tab-content");var a=$(this).children();if(0<a.length){var b=$('<ul class="nav nav-tabs" role="tablist"></ul>');
$(this).before(b);a.each(function(){$(this).attr("role","tabpanel").addClass("tab-pane");b.append('<li role="presentation"><a class="'+$(this).attr("class")+'" href="#'+$(this).attr("id")+'" aria-controls="'+$(this).attr("id")+'" role="tab" data-toggle="tab">'+$(this).attr("data-label")+"</a></li>")});b.find("li:first-child").addClass("active");a.eq(0).addClass("active")}});b&&UI_bindFunction(c.prev('[role="tablist"]').find('[data-toggle="tab"]'),b,"show.bs.tab")},UI_showTab=function(a){if(0==$('[href="#'+
a+'"]').length)return!1;$('[href="#'+a+'"]').tab("show")},UI_createNavBar=function(a,b,c){if(0==$(a).length)return!1;var d=$(a);b&&UI_createJsonUL(a,b);d.addClass("collapse navbar-collapse");d.children("ul").addClass("nav navbar-nav");d.wrap('<nav class="navbar"><div class="container-fluid"></div></nav>');d.before('<div class="navbar-header"><button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#'+d.attr("id")+'"aria-expanded="false"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="#">MAS</a></div>');
d.find("ul.nav.navbar-nav > li").each(function(){0<$(this).find("ul").length&&($(this).addClass("dropdown"),$(this).children("a").addClass("dropdown-toggle").attr({"data-toggle":"dropdown",role:"button","aria-haspopup":!0}).append('<span class="caret"></span>'),$(this).children("ul").addClass("dropdown-menu"))});UI_applyTheme("nav.navbar",c,"navbar-fixed-top navbar-")},UI_createJsonUL=function(a,b){if(0==$(a).length)return!1;var c=$(a),d=$("<ul></ul>");c.append(d);b.attr&&d.attr(b.attr);b["class"]&&
d.addClass(b["class"]);for(var c=b.html,e=0;e<c.length;e++)if(d.append('<li><a href="'+c[e].link+'">'+c[e].label+"</a></li>"),c[e].attr&&d.find("li").eq(e).attr(c[e].attr),c[e].css&&d.find("li").eq(e).attr(c[e].css),c[e]["class"]&&d.find("li").eq(e).addClass(c[e]["class"]),c[e].dropdowndata){d.find("li").eq(e).append("<ul></ul>");for(var h=d.find("li").eq(e).children("ul"),g=c[e].dropdowndata,f=0;f<g.length;f++)h.append('<li><a href="'+g[f].link+'">'+g[f].label+"</a></li>"),g[f].attr&&h.find("li").eq(f).attr(g[f].attr),
g[f].css&&h.find("li").eq(f).attr(g[f].css),g[f]["class"]&&h.find("li").eq(f).addClass(g[f]["class"])}},UI_createDropdown=function(a,b){if(0==$(a).length)return!1;var c=$(a);b&&UI_createJsonUL(a,b);c.addClass("btn-group");c.prepend('<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'+c.attr("data-label")+'<span class="caret"></span></button>');c.find("ul").addClass("dropdown-menu")},UI_createGrid=function(){},UI_refreshGrid=
function(){},UI_destroyModal=function(){},UI_setTooltip=function(){},UI_createTextArea=function(){},UI_createSelectBox=function(){},UI_resetInputValue=function(){},UI_createCustomScroll=function(a){if(0==$(a).length)return!1;var b=$(a).addClass("scrolltargetElement");b.parent().hasClass("ui_scroll_custom")?a=$(a).closest(".ui_scroll_custom"):(b.wrap('<div class="ui_scroll_custom"></div>'),a=$(a).closest(".ui_scroll_custom"),a.append('<div class="scrollbar"><div class="scroller"></div></div>'));b.css({"margin-right":"-30px",
"padding-right":"30px",overflow:"auto","-webkit-user-select":"none","-moz-user-select":"none","-ms-user-select":"none","user-select":"none"});var c=a.find(".scroller");a.find(".scrollbar").on("click",function(a){var b=$(this).find(".scroller").css("height"),c=$(this).closest(".ui_scroll_custom").find(".scrolltargetElement");c.animate({scrollTop:(a.offsetY-parseInt(b)/2)*c[0].scrollHeight/c[0].clientHeight})});c.css("height",b[0].clientHeight*b[0].clientHeight/b[0].scrollHeight+"px");c.css("top",b[0].scrollTop*
b[0].clientHeight/b[0].scrollHeight+"px");b.on("scroll",function(){b.closest(".ui_scroll_custom").find(".scroller").css("top",b[0].scrollTop*b[0].clientHeight/b[0].scrollHeight+"px")})},UI_alert=function(a){0==$("#alert-box-container").length&&($("footer").append('<div id="alert-box-container" data-keyboard=false data-backdrop="static"><div></div><div></div><div></div></div>'),UI_createModal("#alert-box-container"));var b=$("#alert-box-container");b.find(".modal-header > div:last-child").html('<div class="alert alert-warning" role="alert"><a href="#" class="alert-link">'+
a+"</a></div>");b.find(".modal-footer > div:last-child").html('<button class="btn btn-primary btn-small" onclick="UI_closeModal(\'#alert-box-container\')">OK</button>');UI_openModal("#alert-box-container")};