var renderProfileData=function(){getProfileInformationData()},getProfileData=function(a){switch($(a.currentTarget).attr("href")){case "#profileInformation":getProfileInformationData();break;case "#savedBookmarks":getBookmarkdata(0,10);break;case "#savedCurations":getCurationdata()}},getProfileInformationData=function(){(new CommonUtils.remoteCallClass).asyncGetRequest("./"+dataRequestURL+"?request=user_profile_read",profileDataRequestCallback)},profileDataRequestCallback=function(a){a=JSON.parse(a);
if(validateAppResponse(a)){a=a.data;var b=$("#profileInformation");b.find(".profile-firstName").html(a.firstName);b.find(".profile-lastName").html(a.lastName);b.find(".profile-age").html(a.age);b.find(".profile-location").html(a.location);b.find(".profile-phone").html(a.phone)}},getBookmarkdata=function(a,b){data.profileBookmark={};(new CommonUtils.remoteCallClass).asyncGetRequest("./"+dataRequestURL+"?request=bookmark_read&data[videoid]=*&data[startIndex]="+a+"&data[numRows]="+b,bookmarkDataRequestCallback)},
bookmarkDataRequestCallback=function(a){a=JSON.parse(a);validateAppResponse(a)&&(data.profileBookmark=a.data,showBookmarkdata())},getCurationdata=function(){showCurationdata()},showProfileInformationData=function(){},showBookmarkdata=function(){if(0<Object.keys(data.profileBookmark).length){bookMarkListObject=new _ListWidget_.createList({documents:data.profileBookmark});bookMarkListObject.generateBookmarksList("#bookmarkListContainer > .container-fluid");for(var a in data.profileBookmark)IsValueNull(contentObj[data.profileBookmark[a].videoid])&&
(contentObj[data.profileBookmark[a].videoid]=[],contentObj[data.profileBookmark[a].videoid].url="https://www.youtube.com/watch?v=",contentObj[data.profileBookmark[a].videoid].videoid=data.profileBookmark[a].sourcevideoid.replace("yt-",""));data.modify=!0}setHistoryData()},playUserBookmark=function(a){var b=$(a.currentTarget).closest("[data-bookmark-id]").attr("data-bookmark-id");UI_blockInterface();data.bookMarkTopicsData={status:!0,data:data.profileBookmark};data.bookMarkTopicsArr=[];data.playBookmark=
!0;progressChange(10);$("body").animate({scrollTop:0},300);$(".contentSpecificVisible").css("display","none");var c=window.location.search.replace("?","").split("&");c.splice(0,1);DisplayPage("view");progressChange(30);data.videoID=$(a.target).closest("[data-vidId]").attr("data-vidId");renderViewData();urlParamStr=c.join("&");urlParamStr="bookmark="+b;urlStr="getData=view";urlParamStr="&"+urlParamStr+"&videoId="+data.videoID+"&contentsrc="+getVideoSourceType("https://www.youtube.com/watch?v=")+"&sourcevidid="+
data.bookMarkTopicsData.data[data.videoID].sourcevideoid;data.modify=!0;setHistoryData();a.preventDefault();toggleSmallScreenControls("",!1)},showCurationdata=function(){},editProfileInformation=function(a){$(".profileUpdateMessageBox").html("");$(".editOption").addClass("hidden");$(".actionButton").removeClass("hidden");a=$("#generalInfoUpdate");var b=a.find("input");a.find(".display-entry").addClass("hidden");b.each(function(){$(this).removeClass("hidden").val($(this).next(".display-entry").html())})},
saveProfileInformation=function(a){var b=$("#generalInfoUpdate");a=new CommonUtils.remoteCallClass;if(b.hasClass("hidden")){var b=$("#passwordUpdateForm"),c=b.find("#current-password").val(),d=b.find("#new-password").val(),b=b.find("#confirm-password").val();if(d!=b)return $(".profileUpdateMessageBox").html("New password and confirm password do not match").addClass("bg-danger"),!1;a.requestData={request:"user_profile_save",data:{current_password:c,password:d}}}else{var c=b.find("#sign-in-firstname").val()+
" "+b.find("#sign-in-lastname").val(),d=b.find("#sign-in-age").val(),e=b.find("#sign-in-location").val(),b=b.find("#sign-in-phone").val();a.requestData={request:"user_profile_save",data:{username:c,age:d,location:e,phone:b}}}a.syncPostRequest("./"+dataRequestURL,profileInfoSaveRequestCallback)},profileInfoSaveRequestCallback=function(a){a=JSON.parse(a);$(".profileUpdateMessageBox").removeClass("bg-success,bg-danger");var b=validateAppResponse(a),c=$("#generalInfoUpdate");b?c.hasClass("hidden")?$(".profileUpdateMessageBox").html("Password updated successfully").addClass("bg-success"):
$(".profileUpdateMessageBox").html("Profile updated successfully").addClass("bg-success"):(IsValueNull(a.error)&&(a.error="Profile not updated"),$(".profileUpdateMessageBox").html(a.error).addClass("bg-danger"));$(".editOption").removeClass("hidden");$(".actionButton").addClass("hidden");c.hasClass("hidden")?(c.removeClass("hidden"),c=$("#passwordUpdateForm"),c.addClass("hidden"),c.find("input").each(function(){this.value=""})):(a=c.find("input"),c.find(".display-entry").removeClass("hidden"),a.each(function(){$(this).next(".display-entry").html($(this).val());
$(this).addClass("hidden").val("")}))},cancelEditProfileInformation=function(a){$("#generalInfoUpdate").removeClass("hidden");$("#passwordUpdateForm").addClass("hidden");$(".actionButton").addClass("hidden");$(".editOption").removeClass("hidden");a=$("#generalInfoUpdate");var b=a.find("input");a.find(".display-entry").removeClass("hidden");b.each(function(){$(this).addClass("hidden").val("")})},changePasswordInformation=function(a){$(".profileUpdateMessageBox").html("");$(".editOption").addClass("hidden");
$(".actionButton").removeClass("hidden");$("#generalInfoUpdate").addClass("hidden");$("#passwordUpdateForm").removeClass("hidden").find("input")};