var gPlayerList=[],gPlayerObject=0,gTimerObj=0,gEventTypes={ON_END:0,ON_PLAY:1,ON_PAUSE:2,ON_BUFFERING:3,ON_ERROR:4};sVideoSegment.prototype.startTime=0;sVideoSegment.prototype.endTime=0;function sVideoSegment(){sVideoSegment.prototype.startTime=0;sVideoSegment.prototype.endTime=0}
function CreatePlayerWidget(a,b,c,d,e,f){if(gPlayerObject)return gPlayerObject;gPlayerObject=new CVideoPlayer(a,b,c,d,e,f);if("YT"==a)a=document.createElement("script"),date=new Date,time=date.getTime(),a.src="https://www.youtube.com/iframe_api?"+time,b=document.getElementsByTagName("script")[0],b.parentNode.insertBefore(a,b);else return 0;return gPlayerObject}
function onYouTubeIframeAPIReady(){gPlayerObject.playerHandle=new YT.Player(gPlayerObject.iFrameID,{width:gPlayerObject.Width,height:gPlayerObject.Height,playerVars:{autoplay:0,controls:gPlayerObject.Controls,frameborder:1,modestbranding:1,rel:0,showinfo:0},events:{onReady:OnYTPlayerReady,onStateChange:gPlayerObject.onPlayerStateChange,onError:gPlayerObject.onPlayerError}});document.getElementById(gPlayerObject.iFrameID);0==gPlayerObject.bShow&&gPlayerObject.ShowVideoPlayer(gPlayerObject.bShow);gPlayerObject.bInitialized=
!0;gPlayerObject.playerState="STOPPED"}
function CVideoPlayer(a,b,c,d,e,f){this.playerType=a;this.iFrameID=b;this.Width=c;this.Height=d;this.bShow=e;this.Controls=1==f?1:0;this.CurrentDisplay="VISIBLE";this.playerHandle=0;this.playerState="VOID";this.endPTS=this.startPTS=this.currentPTS=0;this.playSegmentFlag=this.bInitialized=!1;this.OnBufferingHandlerFn=this.OnEndHandlderFn=this.OnPauseHandlerfn=this.OnPlayHandlerFn=this.OnErrorHandlerFn=this.currentVideoID=this.SegmentList=this.currentSegIndex=this.segmentHandlerfn=0}
CVideoPlayer.prototype.LoadNewVideoByID=function(a,b){this.currentVideoID=a;"undefined"!=this.playerHandle&&(this.ShowVideoPlayer(!0),"PLAYING"==this.playerState&&(this.playerHandle.stopVideo(),this.playerHandle.clearVideo()),this.playerHandle.loadVideoById({videoId:a,startSeconds:b}),this.playerState="PLAYING",this.videoID=a,playSegmentFlag=!1)};CVideoPlayer.prototype.UnloadVideo=function(){this.playerHandle.pauseVideo();this.playerHandle.stopVideo();this.playerHandle.clearVideo()};
CVideoPlayer.prototype.ShowVideoPlayer=function(a){var b=document.getElementById(this.iFrameID);0==a?(b.setAttribute("hidden",!0),this.CurrentDisplay="HIDDEN"):(b.removeAttribute("hidden"),this.CurrentDisplay="VISIBLE")};function CheckIfPlayerExists(a){}CVideoPlayer.prototype.onPlayerReady=function(a){a.target.setVolume(70);a.target.playVideo()};CVideoPlayer.prototype.Play=function(){this.playerHandle.playVideo()};CVideoPlayer.prototype.Pause=function(){this.playerHandle.pauseVideo()};
CVideoPlayer.prototype.SeekTo=function(a){this.playerHandle.seekTo(a)};CVideoPlayer.prototype.GetCurrentPTS=function(a){return this.playerHandle.getCurrentTime()};CVideoPlayer.prototype.GetPlayerState=function(a){return this.playerHandle.getPlayerState()};
CVideoPlayer.prototype.onPlayerStateChange=function(a){var b="",b=0;switch(a.data){case gEventTypes.ON_PLAY:a=new Number(gPlayerObject.GetCurrentPTS());b=new Number(gPlayerObject.endPTS-a);b*=1E3;1==gPlayerObject.playSegmentFlag?(a=gPlayerObject.FindSegmentIndex(a),-1!=a&&a!=gPlayerObject.currentSegIndex&&(gPlayerObject.Pause(),gPlayerObject.currentSegIndex=a,gPlayerObject.endPTS=gPlayerObject.SegmentList[gPlayerObject.currentSegIndex].endTime,a=new Number(gPlayerObject.GetCurrentPTS()),b=new Number(gPlayerObject.endPTS-
a),b*=1E3,gPlayerObject.Play(),eval(gPlayerObject.segmentHandlerfn+"("+gPlayerObject.currentSegIndex+")")),gTimerObj=setTimeout(function(){if(gPlayerObject.SegmentList)if(gPlayerObject.currentSegIndex<gPlayerObject.SegmentList.length)if(gPlayerObject.currentSegIndex++,gPlayerObject.currentSegIndex<gPlayerObject.SegmentList.length){gPlayerObject.PlaySegmentIndex(gPlayerObject.currentSegIndex);var a=gPlayerObject.segmentHandlerfn+"("+gPlayerObject.currentSegIndex+")";eval(a)}else gPlayerObject.playerHandle.stopVideo();
else gPlayerObject.playerHandle.stopVideo();else a=gPlayerObject.segmentHandlerfn+"()",eval(a)},b)):gPlayerObject.OnPlayHandlerFn&&(b=gPlayerObject.OnPlayHandlerFn+"()",eval(b));break;case gEventTypes.ON_PAUSE:1==gPlayerObject.playSegmentFlag?gTimerObj&&(clearTimeout(gTimerObj),gTimerObj=0):gPlayerObject.OnPauseHandlerfn&&(b=gPlayerObject.OnPauseHandlerfn+"()",eval(b));break;case gEventTypes.ON_BUFFERING:1==gPlayerObject.playSegmentFlag?gTimerObj&&(clearTimeout(gTimerObj),gTimerObj=0):gPlayerObject.OnBufferingHandlerFn&&
(b=gPlayerObject.OnBufferingHandlerFn+"()",eval(b));break;case gEventTypes.ON_END:gPlayerObject.OnEndHandlderFn&&(b=gPlayerObject.OnEndHandlderFn+"()",eval(b)),1==gPlayerObject.playSegmentFlag&&gTimerObj&&(clearTimeout(gTimerObj),gTimerObj=0)}};CVideoPlayer.prototype.onPlayerError=function(a){a="";gPlayerObject.OnErrorHandlerFn&&(a=gPlayerObject.OnErrorHandlerFn+"(errorcode)",eval(a))};
CVideoPlayer.prototype.LoadNewVideoSegment=function(a,b){this.SegmentList=0;this.videoID=this.currentVideoID=a;this.segmentHandlerfn=b;"undefined"!=this.playerHandle&&(this.ShowVideoPlayer(!0),"PLAYING"==this.playerState&&(this.playerHandle.stopVideo(),this.playerHandle.clearVideo()));this.playerHandle.loadVideoById({videoId:this.currentVideoID});this.playSegmentFlag=!0;this.Pause()};
CVideoPlayer.prototype.LoadVideoWithSegmentList=function(a,b,c){this.currentVideoID=a;"undefined"!=this.playerHandle&&(this.ShowVideoPlayer(!0),"PLAYING"==this.playerState&&(this.playerHandle.stopVideo(),this.playerHandle.clearVideo()));this.segmentHandlerfn=c;a=b.length;this.SegmentList=[];for(i=0;i<a;i++)this.SegmentList.push(b[i]);this.playerHandle.loadVideoById({videoId:this.currentVideoID});this.playSegmentFlag=!0;this.currentSegIndex=0;this.Pause();this.PlaySegmentIndex(this.currentSegIndex);
eval(this.segmentHandlerfn+"("+this.currentSegIndex+")")};CVideoPlayer.prototype.PlaySegmentIndex=function(a){a=this.SegmentList[a];this.startPTS=a.startTime;this.endPTS=a.endTime;if(0>new Number(1E3*(this.endPTS-this.startPTS)))return 0;this.SeekTo(new Number(this.startPTS));this.Play()};CVideoPlayer.prototype.PlaySegmentwise=function(a,b){this.startPTS=a;this.endPTS=b;if(0>new Number(1E3*(b-a)))return 0;this.SeekTo(new Number(a));this.Play()};
CVideoPlayer.prototype.PlayWithinInterval=function(a,b){var c=new Number(1E3*(b-a));0>c||(this.SeekTo(new Number(a)),this.Play(),setTimeout(function(){gPlayerObject.Pause()},c))};
CVideoPlayer.prototype.SetEventHandler=function(a,b){switch(a){case gEventTypes.ON_PLAY:this.OnPlayHandlerFn=b;break;case gEventTypes.ON_PAUSE:this.OnPauseHandlerfn=b;break;case gEventTypes.ON_ERROR:this.OnErrorHandlerFn=b;break;case gEventTypes.ON_BUFFERING:this.OnBufferingHandlerFn=b;break;case gEventTypes.ON_END:this.OnEndHandlderFn=b}};
CVideoPlayer.prototype.RemovetEventHandler=function(a){switch(a){case gEventTypes.ON_PLAY:this.OnPlayHandlerFn=0;break;case gEventTypes.ON_PAUSE:this.OnPauseHandlerfn=0;break;case gEventTypes.ON_ERROR:this.OnErrorHandlerFn=0;break;case gEventTypes.ON_BUFFERING:this.OnBufferingHandlerFn=0;break;case gEventTypes.ON_END:this.OnEndHandlderFn=0}};
CVideoPlayer.prototype.FindSegmentIndex=function(a){for(var b=0;b<this.SegmentList.length;b++)if(a>=this.SegmentList[b].startTime&&a<=this.SegmentList[b].endTime)return b;return-1};